disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "The Tinkering Mind"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2, 2006"
logo = "the-tinkering-mind.png"

  [params.author]
  name = "Ankit Patterson"
  image = "me.jpg"
  headline = "Tinkerer, Coder, Dog Lover"
  bio = "A tinkerer, coder, and occasional writer."

    [[params.author.links]]
    bluesky = "https://bsky.app/profile/weirdion.bsky.social"

    [[params.author.links]]
    github = "https://github.com/weirdion"

    [[params.author.links]]
    linkedin = "https://linkedin.com/in/ankitpatterson"
