[[main]]
name = "Home"
url = "/"
weight = 10

[[main]]
name = "Posts"
pageRef = "posts"
weight = 10

[[main]]
pre = "bluesky"
url = "https://bsky.app/profile/weirdion.bsky.social"
identifier = "QMrAhbanbr"
weight = 9_999

[[main]]
pre = "github"
url = "https://github.com/weirdion"
identifier = "DMxHV1FiWw"
weight = 9_999

[[main]]
pre = "linkedin"
url = "https://linkedin.com/in/ankitpatterson"
identifier = "gNXC3L3WwT"
weight = 9_999

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10
