title: Ankit Patterson's Blog
description: A blog to document my tinkerings and learnings.
baseurl: "/"
url: "https://weirdion.github.io"
theme: minima

# minima configuration for < 3.0
show_excerpts: true
github_username:  weirdion
linkedin_username: ankitpatterson
bluesky_username: weirdion.bsky.social
author: "Ankit Patterson"

social_links:
  github:

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-tagging
collections:
  posts:
    output: true
    permalink: /posts/:title/
permalink: /:categories/:year/:month/:day/:title/
paginate: 10
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ankit Patterson"
