baseURL = "https://weirdion.github.io/"
languageCode = "en-us"
title = "The Tinkering Mind"
theme = "PaperMod"

[params]
  author = "Ankit Patterson"
  description = "Some practical description of your blog."
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  showtoc = true
  tocopen = true

[menu]
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2
